[2024-02-29 09:12:43,845] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: email_teste.tsk4 2024-02-29T09:12:23.583432+00:00 [queued]>
[2024-02-29 09:12:43,872] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: email_teste.tsk4 2024-02-29T09:12:23.583432+00:00 [queued]>
[2024-02-29 09:12:43,873] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 09:12:43,873] {taskinstance.py:1096} INFO - Starting attempt 2 of 2
[2024-02-29 09:12:43,873] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-02-29 09:12:43,902] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): tsk4> on 2024-02-29T09:12:23.583432+00:00
[2024-02-29 09:12:43,911] {standard_task_runner.py:52} INFO - Started process 72 to run task
[2024-02-29 09:12:43,917] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'email_teste', 'tsk4', '2024-02-29T09:12:23.583432+00:00', '--job-id', '233', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpavs0z0x_', '--error-file', '/tmp/tmpcupfeo9d']
[2024-02-29 09:12:43,917] {standard_task_runner.py:77} INFO - Job 233: Subtask tsk4
[2024-02-29 09:12:43,993] {logging_mixin.py:109} INFO - Running <TaskInstance: email_teste.tsk4 2024-02-29T09:12:23.583432+00:00 [running]> on host cf1345502425
[2024-02-29 09:12:44,089] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jezandre_tiago@hotmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_teste
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-02-29T09:12:23.583432+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-29T09:12:23.583432+00:00
[2024-02-29 09:12:44,091] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-02-29 09:12:44,092] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 1']
[2024-02-29 09:12:44,110] {subprocess.py:74} INFO - Output:
[2024-02-29 09:12:44,115] {subprocess.py:82} INFO - Command exited with return code 1
[2024-02-29 09:12:44,143] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2024-02-29 09:12:44,147] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=email_teste, task_id=tsk4, execution_date=20240229T091223, start_date=20240229T091243, end_date=20240229T091244
[2024-02-29 09:12:44,240] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/email.py:102 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-02-29 09:12:44,241] {email.py:208} INFO - Email alerting: attempt 1
[2024-02-29 09:12:48,260] {email.py:220} INFO - Sent an alert email to ['jezandre_tiago@hotmail.com']
[2024-02-29 09:12:49,874] {local_task_job.py:151} INFO - Task exited with return code 1
[2024-02-29 09:12:49,961] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
